Repository KernelTestFramework/ktf, pull requests merged in 2020-09, with the labels that each got.

#91 string[1/2]: added more string manipulation functions.
  include/string.h
  lib/string.c
Labels: devel, improvement

#96 acpi: MADT: do not count disabled CPUs
  common/acpi.c
Labels: bug

#99 drivers: add basic PIC initialization
  common/setup.c
  drivers/pic.c
  include/drivers/pic.h
Labels: feature, improvement
