Repository KernelTestFramework/ktf, pull requests merged in 2020-10, with the labels that each got.

#105 Add docker build test workflow
  .github/workflows/docker-build.yml
Labels: build infra

#106 pagetables: harden get_pgentry_mfn()
  arch/x86/pagetables.c
Labels: Severity: low, bugfix

#107 ACPI: fix multi-page ACPI table allocation
  common/acpi.c
  include/acpi.h
Labels: Severity: high, bugfix

#114 acpi: use ACPI config by default
  common/acpi.c
  common/setup.c
  include/acpi.h
  include/smp/mptables.h
  smp/mptables.c
  smp/smp.c
Labels: Severity: medium, bug, improvement

#120 workflows: add one-line-cr-bot
  .github/workflows/one-line-cr-bot.yml
Labels: build infra, static analysis

#122 static-analysis: make BUG an infinite-loop
  include/lib.h
Labels: Severity: critical, bug, build infra, static analysis

#123 slab: Add kmalloc, kzalloc and kfree wrappers
  arch/x86/ioapic.c
  common/setup.c
  include/mm/slab.h
  include/string.h
  mm/slab.c
Labels: cleanup, improvement

#126 workflow: fox Docker build workflow transient failures
  .github/workflows/docker-build.yml
  README.md
Labels: bugfix, build infra

#127 ioapic: move init_ioapic() to .text.init section
  arch/x86/ioapic.c
Labels: cleanup

#128 setup: track BSP CPU ID via common interface
  common/acpi.c
  common/percpu.c
  common/setup.c
  include/acpi.h
  include/percpu.h
  include/setup.h
  smp/mptables.c
  smp/smp.c
Labels: cleanup, improvement
