Repository KernelTestFramework/ktf, pull requests merged in 2020-11, with the labels that each got.

#130 percpu: add PERCPU variables handling macros
  arch/x86/traps.c
  common/kernel.c
  include/compiler.h
  include/percpu.h
  smp/smp.c
Labels: Priority: 3, devel, improvement

#156 pagetable fixes: zero cr3 page and lower 1MB kernel va range
  arch/x86/pagetables.c
  mm/pmm.c
Labels: Severity: critical, bugfix

#160 Larger kernel binary: increase virtual address mappings at boot
  arch/x86/boot/pagetables.S
  include/arch/x86/pagetable.h
Labels: feature, improvement
