Repository KernelTestFramework/ktf, pull requests merged in 2023-08, with the labels that each got.

#279 sched: add task repetition functionality
  common/sched.c
  include/sched.h
  tests/unittests.c
Labels: improvement

#281 pmm: properly detect first available memory region
  mm/pmm.c
Labels: bugfix

#287 Improved framebuffer text scrolling mechanism
  common/cmdline.c
  drivers/fb/fb.c
  include/cmdline.h
  include/drivers/fb.h
Labels: improvement

#288 x86,traps: #DF IST stack has to be mapped in user page tables
  arch/x86/traps.c
Labels: bugfix, Severity: high

#286 Makefile: add boot_gfx target
  Makefile
Labels: devel, build infra

#289 Further fixes for usermode handling
  arch/x86/entry.S
  arch/x86/pagetables.c
  common/usermode.c
Labels: cleanup, bugfix

#298 entry: SAVE/RESTORE_ALL_REGS cond. exclude AX
  arch/x86/entry.S
  include/arch/x86/asm-macros.h
Labels: bugfix, Severity: critical

#301 README, Makefile: adjust targets.
  Makefile
  README.md
Labels: documentation, Priority: 4

#302 usermode: set return code correctly
  arch/x86/entry.S
  tests/unittests.c
Labels: bug, Severity: medium
