Repository KernelTestFramework/ktf, pull requests merged in 2023-11, with the labels that each got.

#315 string: fix strdup() too little space allocation
  include/string.h
Labels: bugfix, Severity: high

#316 entry: disable interrupts during usermode transition
  arch/x86/entry.S
  arch/x86/traps.c
  include/arch/x86/segment.h
Labels: bugfix, Severity: high

#327 vmm: don't vmap non-canonical addresses
  arch/x86/pagetables.c
  include/arch/x86/page.h
  include/bitmap.h
  include/compiler.h
Labels: improvement, Priority: 4

#329 Fix asm-offset headers (re)generation; Generate binary with debug symbols
  Makefile
  README.md
  tools/ci/build-docker.sh
  tools/ci/launch-test.sh
  tools/xen_config/config
Labels: cleanup, bugfix, build infra

#334 qemu: Improve KVM detection and export QEMU settings to a config file
  .qemu_config
  Makefile
Labels: build infra

#336 acpi,smp: always use APIC ID for CPU identifiers
  common/acpi.c
  common/percpu.c
  include/percpu.h
Labels: improvement, cleanup, bugfix
